name: Merge Main to Test

on:
  push:
    branches:
      - main

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Fetch all branches
      run: git fetch --all

    - name: Merge main into test
      run: |
        git checkout test
        git merge origin/main --no-edit --allow-unrelated-histories

    - name: Push changes to test
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: git push origin test
